// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    
		int num = Integer.parseInt(args[0]);

		int countBigger = 0;
		int countSmaller = 0;
		double ratio;

		for(int i = 0 ; i < num ; i++){
			double random = Math.random();
			if(random>0.5){
				countBigger++;
			}
			else{
				countSmaller++;
			}
		}

		ratio = (double) countBigger/countSmaller;

		System.out.println("num> 0.5: " + countBigger +  " times");
		System.out.println("num<= 0.5: " + countSmaller +  " times");
		System.out.println("Ratio: " + ratio);


	}
}
